use serde::Serialize;

pub const PERSONAL_CATALOG_VERSION: &str = "nanzhufeng-personal-catalog-v2";

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct PersonalCatalogDomain {
    pub key: String,
    pub name: String,
    pub description: String,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct PersonalCatalogTopic {
    pub key: String,
    pub domain_key: String,
    pub parent_key: Option<String>,
    pub name: String,
    pub description: String,
    pub topic_kind: String,
    pub aliases: Vec<String>,
    pub entities: Vec<String>,
    pub keywords: Vec<String>,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct PersonalCatalogProposal {
    pub version: String,
    pub status: String,
    pub title: String,
    pub note: String,
    pub domains: Vec<PersonalCatalogDomain>,
    pub topics: Vec<PersonalCatalogTopic>,
}

pub fn personal_catalog_proposal() -> PersonalCatalogProposal {
    PersonalCatalogProposal {
        version: PERSONAL_CATALOG_VERSION.to_string(),
        status: "proposal".to_string(),
        title: "南烛枫个人主题目录 v2".to_string(),
        note: "按内容主体重构为投资、AI/软件、影视创作、海外账号与金融、汽车、医疗、教育和长期事务。默认规则只使用能独立说明主题的短语；确认只补充缺失项并停用旧版宽泛规则，不覆盖原文、已有归类或用户自建规则。".to_string(),
        domains: vec![
            domain("investment", "投资研究", "公司、行业、资产与投资判断"),
            domain("ai-software", "AI 与软件", "模型、Agent、软件开发与知识工作流"),
            domain("vfx", "影视、动画与 VFX", "合成、动画、镜头复盘与媒体处理"),
            domain("accounts", "海外账号", "账号体系、银行支付、通信号码与风险事项"),
            domain("automotive", "汽车与出行", "车型、用车、产业与出行决策"),
            domain("health", "医疗健康", "疾病、检查、用药、血型与就医决策"),
            domain("education", "教育与升学", "专业选择、院校报考与职业发展"),
            domain("life", "长期事务", "居住、设备、环境与长期生活事项"),
        ],
        topics: vec![
            topic(
                "investment-a-share",
                "investment",
                None,
                "A股与基金市场",
                "中国股票、基金、交易制度与市场规则",
                &["A股交易", "股票交易制度", "证券市场规则"],
                &["上交所", "深交所", "证监会"],
                &[
                    "A股",
                    "股票交易",
                    "涨跌幅限制",
                    "盘后固定价格交易",
                    "创业板交易",
                    "公募基金",
                    "ETF 基金",
                ],
            ),
            topic(
                "investment-ai-infra",
                "investment",
                None,
                "AI 基础设施",
                "算力、数据中心、云厂商与产业链",
                &["AI 算力", "数据中心产业链"],
                &["英伟达", "NVIDIA", "数据中心"],
                &["AI 算力", "训练集群", "推理集群", "数据中心电力"],
            ),
            topic(
                "investment-ai-capex",
                "investment",
                Some("investment-ai-infra"),
                "资本开支与现金流",
                "AI 资本开支周期、折旧和自由现金流",
                &["AI 资本开支", "CapEx"],
                &["自由现金流", "云厂商资本开支"],
                &["AI 资本开支", "资本开支周期", "服务器折旧", "自由现金流"],
            ),
            topic(
                "ai-model-cost",
                "ai-software",
                None,
                "模型与成本",
                "大模型能力、价格、额度和推理成本",
                &["模型价格", "Token 成本"],
                &["OpenAI API", "Claude API", "Gemini API"],
                &["大模型价格", "API 计费", "Token 成本", "推理成本", "模型额度"],
            ),
            topic(
                "ai-agent-workflow",
                "ai-software",
                None,
                "Agent 与 Codex 工作流",
                "代理工具、上下文、插件和自动化协作",
                &["Codex 工作流", "Agent 工作流"],
                &["OpenAI Codex", "MCP 协议"],
                &["Agent 工作流", "Codex 任务", "工具调用", "上下文工程", "MCP 插件"],
            ),
            topic(
                "ai-software-development",
                "ai-software",
                None,
                "软件开发",
                "面向工作流自动化和实用工具的软件工程",
                &["编程开发", "开发工具"],
                &["Windows 桌面应用", "Android 应用", "GitHub 仓库"],
                &["软件开发", "代码调试", "自动化测试", "生产构建", "桌面软件"],
            ),
            topic(
                "ai-knowledge-workflow",
                "ai-software",
                None,
                "知识库与检索",
                "本地优先知识库、搜索、证据和开放文件交换",
                &["个人知识库", "开放文件工作流"],
                &["SQLite 知识库", "Obsidian 知识库"],
                &["个人知识库", "全文检索", "知识证据链", "本地优先", "Markdown 交换"],
            ),
            topic(
                "vfx-compositing",
                "vfx",
                None,
                "合成工作流",
                "Fusion、颜色管理、镜头合成和复盘",
                &["Fusion 合成", "VFX 合成"],
                &["DaVinci Fusion", "Nuke 合成"],
                &["镜头合成", "预乘去边", "颜色空间管理", "ACES 色彩管理", "运动模糊合成"],
            ),
            topic(
                "vfx-animation",
                "vfx",
                None,
                "动画与动效",
                "动画设计、运动语言和界面动效",
                &["Motion Design", "动效设计"],
                &["After Effects 动效"],
                &["角色动画", "关键帧动画", "界面动效", "缓动曲线", "镜头转场"],
            ),
            topic(
                "vfx-transcription",
                "vfx",
                None,
                "音视频转写",
                "字幕、语音识别、时间码和内容整理",
                &["字幕整理", "视频转写"],
                &["Whisper 转写", "SRT 字幕", "VTT 字幕"],
                &["音频转写", "视频转写", "字幕时间码", "语音识别"],
            ),
            topic(
                "vfx-image-generation",
                "vfx",
                None,
                "AI 图像与视觉创作",
                "人物、场景、参考图和生成式视觉方案",
                &["AI 图像生成", "生成式视觉创作"],
                &["Midjourney", "Stable Diffusion"],
                &["生成画面", "参考图生成", "人物形象", "生成一张图片", "绘画提示词"],
            ),
            topic(
                "accounts-system",
                "accounts",
                None,
                "海外账号体系",
                "跨地区账号、身份区域、登录与服务可用性",
                &["跨区账号", "海外平台账号"],
                &["Apple ID 账号", "Google 账号"],
                &["美区 Apple ID", "港区 Apple ID", "账号地区", "跨区登录", "海外账号"],
            ),
            topic(
                "accounts-banking",
                "accounts",
                None,
                "海外银行与支付",
                "海外银行卡、银行账户、券商账户和跨境支付",
                &["海外银行卡", "美国银行卡", "香港银行卡"],
                &["HSBC HK", "Charles Schwab", "IBKR", "Wise", "PayPal"],
                &["海外银行", "银行卡申请", "借记卡方案", "信用卡方案", "跨境支付", "券商账户"],
            ),
            topic(
                "accounts-telecom",
                "accounts",
                None,
                "海外通信与号码",
                "境外手机卡、Wi-Fi Calling、漫游和号码保留",
                &["海外手机卡", "境外通信服务"],
                &["giffgaff", "Wi-Fi Calling", "VoLTE", "PayGo"],
                &["海外手机卡", "Wi-Fi Calling", "国际漫游", "手机号码保号", "eSIM 套餐"],
            ),
            topic(
                "accounts-risk",
                "accounts",
                None,
                "账号风控与封禁",
                "Google、Apple、支付和地区账号的登录与风控",
                &["海外账号风控", "账号被封"],
                &[],
                &["账号封禁", "登录验证失败", "风险控制", "账号申诉", "身份验证异常"],
            ),
            topic(
                "automotive-new-energy",
                "automotive",
                None,
                "新能源车与二手车",
                "新能源车型、购车选择、二手残值和长期用车",
                &["新能源车选购", "二手新能源车", "车型比较"],
                &["理想 i8", "理想汽车", "极氪汽车", "特斯拉汽车"],
                &["新能源车", "二手车选择", "选车建议", "电池衰减", "车辆保值率", "用车成本"],
            ),
            topic(
                "health-blood",
                "health",
                None,
                "血型与输血",
                "ABO/Rh 血型、红细胞和临床输血兼容",
                &["ABO 血型", "输血兼容"],
                &["A 型血", "B 型血", "O 型血", "AB 型血", "Rh 阴性"],
                &["血型输血", "红细胞输注", "输血反应", "ABO 血型", "交叉配血"],
            ),
            topic(
                "education-art",
                "education",
                None,
                "艺术与设计升学",
                "艺术、设计、数媒和动画专业的院校与志愿选择",
                &["艺术专业报考", "艺术设计升学", "美术专业报考"],
                &["视觉传达专业", "环境艺术设计", "数字媒体艺术"],
                &["艺术专业", "美术专业", "专科报考", "志愿填报", "录取分数", "艺术统考"],
            ),
            topic(
                "life-nanjing-rent",
                "life",
                None,
                "南京租房",
                "区域、租金、通勤和居住环境比较",
                &["南京租房决策", "租房候选"],
                &["南京河西", "南京江宁"],
                &["南京租房", "租金预算", "通勤距离", "居住噪音", "小区停车"],
            ),
            topic(
                "life-equipment",
                "life",
                None,
                "设备与工作环境",
                "电脑、显示器、音频设备与工作空间",
                &["工作环境", "硬件设备"],
                &["Windows 工作站", "Mac 工作站"],
                &["电脑硬件", "显示器选择", "音频设备", "工作室噪音", "设备温度"],
            ),
        ],
    }
}

fn domain(key: &str, name: &str, description: &str) -> PersonalCatalogDomain {
    PersonalCatalogDomain {
        key: key.to_string(),
        name: name.to_string(),
        description: description.to_string(),
    }
}

fn topic(
    key: &str,
    domain_key: &str,
    parent_key: Option<&str>,
    name: &str,
    description: &str,
    aliases: &[&str],
    entities: &[&str],
    keywords: &[&str],
) -> PersonalCatalogTopic {
    PersonalCatalogTopic {
        key: key.to_string(),
        domain_key: domain_key.to_string(),
        parent_key: parent_key.map(str::to_string),
        name: name.to_string(),
        description: description.to_string(),
        topic_kind: "subject".to_string(),
        aliases: aliases.iter().map(|value| (*value).to_string()).collect(),
        entities: entities.iter().map(|value| (*value).to_string()).collect(),
        keywords: keywords.iter().map(|value| (*value).to_string()).collect(),
    }
}
