use serde::Serialize;

pub const PERSONAL_CATALOG_VERSION: &str = "nanzhufeng-personal-catalog-v3";

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct PersonalCatalogDomain {
    pub key: String,
    pub name: String,
    pub description: String,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct PersonalCatalogTopic {
    pub key: String,
    pub domain_key: String,
    pub parent_key: Option<String>,
    pub name: String,
    pub description: String,
    pub topic_kind: String,
    pub aliases: Vec<String>,
    pub entities: Vec<String>,
    pub keywords: Vec<String>,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct PersonalCatalogProposal {
    pub version: String,
    pub status: String,
    pub title: String,
    pub note: String,
    pub domains: Vec<PersonalCatalogDomain>,
    pub topics: Vec<PersonalCatalogTopic>,
}

pub fn personal_catalog_proposal() -> PersonalCatalogProposal {
    PersonalCatalogProposal {
        version: PERSONAL_CATALOG_VERSION.to_string(),
        status: "proposal".to_string(),
        title: "南烛枫个人主题目录 v3".to_string(),
        note: "根据现有资料分布扩展为投资、AI/软件、设计创作、影视/VFX、海外账号与金融、汽车、医疗、教育职业、长期事务和社会文化。默认规则只使用能独立说明主题的短语；确认只补充缺失项并停用旧版宽泛规则，不覆盖原文、已有归类或用户自建规则。".to_string(),
        domains: vec![
            domain("investment", "投资研究", "公司、行业、资产与投资判断"),
            domain("ai-software", "AI 与软件", "模型、Agent、软件开发与知识工作流"),
            domain("vfx", "影视、动画与 VFX", "合成、动画、镜头复盘与媒体处理"),
            domain("accounts", "海外账号", "账号体系、银行支付、通信号码与风险事项"),
            domain("automotive", "汽车与出行", "车型、用车、产业与出行决策"),
            domain("health", "医疗健康", "疾病、检查、用药、血型与就医决策"),
            domain("education", "教育与升学", "专业选择、院校报考与职业发展"),
            domain("life", "长期事务", "居住、设备、环境与长期生活事项"),
            domain("design", "设计与创作", "品牌、图标、界面、图像与视觉表达"),
            domain("culture", "社会与文化", "历史制度、法律家庭、语言与文化作品"),
        ],
        topics: vec![
            topic(
                "investment-a-share",
                "investment",
                None,
                "A股与基金市场",
                "中国股票、基金、交易制度与市场规则",
                &["A股交易", "股票交易制度", "证券市场规则"],
                &["上交所", "深交所", "证监会"],
                &[
                    "A股",
                    "股票交易",
                    "涨跌幅限制",
                    "盘后固定价格交易",
                    "创业板交易",
                    "公募基金",
                    "ETF 基金",
                ],
            ),
            topic(
                "investment-ai-infra",
                "investment",
                None,
                "AI 基础设施",
                "算力、数据中心、云厂商与产业链",
                &["AI 算力", "数据中心产业链"],
                &["英伟达", "NVIDIA", "数据中心"],
                &["云端算力集群", "训练集群", "推理集群", "数据中心电力"],
            ),
            topic(
                "investment-ai-capex",
                "investment",
                Some("investment-ai-infra"),
                "资本开支与现金流",
                "AI 资本开支周期、折旧和自由现金流",
                &["AI 资本开支", "CapEx"],
                &["自由现金流", "云厂商资本开支"],
                &["AI 资本开支", "资本开支周期", "服务器折旧", "自由现金流"],
            ),
            topic(
                "investment-global-equity",
                "investment",
                None,
                "美股与全球市场",
                "美股、港股、海外公司、指数与行业投资研究",
                &["美股投资", "全球股票市场", "港股投资"],
                &["纳斯达克指数", "标普 500 指数", "华尔街"],
                &[
                    "美股分析",
                    "港股分析",
                    "海外公司估值",
                    "美股财报",
                    "全球股市",
                    "纳指 ETF",
                ],
            ),
            topic(
                "investment-semiconductor",
                "investment",
                None,
                "半导体与算力产业",
                "芯片、GPU、CUDA、存储、晶圆制造与算力产业链",
                &["半导体产业", "AI 芯片产业", "算力芯片"],
                &["CUDA 生态", "台积电", "ASML", "英伟达 GPU"],
                &[
                    "半导体投资",
                    "国产 AI 芯片",
                    "存储芯片",
                    "晶圆制造",
                    "芯片产业链",
                    "GPU 竞争力",
                ],
            ),
            topic(
                "investment-macro",
                "investment",
                None,
                "宏观经济与资产配置",
                "经济周期、货币政策、利率、汇率、债券与资产配置",
                &["宏观经济分析", "资产配置", "利率与汇率"],
                &["美联储", "人民币汇率", "美国国债"],
                &[
                    "货币政策",
                    "利率周期",
                    "强美元",
                    "居民贷款",
                    "经济周期",
                    "资金流动",
                ],
            ),
            topic(
                "investment-real-estate",
                "investment",
                None,
                "房地产与楼市研究",
                "国内外房地产周期、房价、房源、土地与住房市场",
                &["房地产市场", "楼市研究", "房价走势"],
                &["日本楼市", "二手房市场", "住房价格指数"],
                &[
                    "楼市跌幅",
                    "房价分析",
                    "房价统计",
                    "房地产周期",
                    "住房市场",
                    "房源统计",
                ],
            ),
            topic(
                "investment-method-risk",
                "investment",
                None,
                "投资方法与风险",
                "估值框架、仓位、投资复盘、风险控制与方法论",
                &["投资风险管理", "投资方法论", "估值与风控"],
                &[],
                &[
                    "投资风险分析",
                    "估值分析",
                    "投资价值分析",
                    "投资复盘",
                    "仓位管理",
                    "投资策略",
                ],
            ),
            topic(
                "ai-model-cost",
                "ai-software",
                None,
                "模型与成本",
                "大模型能力、价格、额度和推理成本",
                &["模型价格", "Token 成本"],
                &["OpenAI API", "Claude API", "Gemini API"],
                &["大模型价格", "API 计费", "Token 成本", "推理成本", "模型额度"],
            ),
            topic(
                "ai-agent-workflow",
                "ai-software",
                None,
                "Agent 与 Codex 工作流",
                "代理工具、上下文、插件和自动化协作",
                &["Codex 工作流", "Agent 工作流"],
                &["OpenAI Codex", "MCP 协议"],
                &["Agent 工作流", "Codex 任务", "工具调用", "上下文工程", "MCP 插件"],
            ),
            topic(
                "ai-software-development",
                "ai-software",
                None,
                "软件开发",
                "面向工作流自动化和实用工具的软件工程",
                &["编程开发", "开发工具"],
                &["Windows 桌面应用", "桌面工作流工具"],
                &["软件开发", "代码调试", "自动化测试", "生产构建", "桌面软件"],
            ),
            topic(
                "ai-git-version-control",
                "ai-software",
                None,
                "Git 与版本控制",
                "Git、GitHub、分支、提交、仓库安全与协作流程",
                &["Git 版本控制", "GitHub 仓库管理", "分支保护"],
                &["GitHub 主分支", "Git 仓库"],
                &[
                    "GitHub 分支保护",
                    "保护 GitHub 主分支",
                    "分支保护规则",
                    "Git 提交历史",
                    "GitHub 登录",
                    "gitignore 配置",
                ],
            ),
            topic(
                "ai-data-recovery",
                "ai-software",
                None,
                "数据备份、迁移与恢复",
                "数据库、应用数据、导入导出、备份、恢复与迁移安全",
                &["数据备份与恢复", "数据迁移", "导入导出"],
                &["SQLite 备份", "应用数据库"],
                &[
                    "账本恢复",
                    "恢复失败",
                    "完整迁移备份",
                    "数据库备份",
                    "数据导出",
                    "备份恢复",
                ],
            ),
            topic(
                "ai-network-connectivity",
                "ai-software",
                None,
                "网络、代理与连接",
                "代理协议、网络连接、证书、节点与连通性排障",
                &["网络连接排障", "代理与节点", "连接问题"],
                &["Clash 代理", "AnyTLS", "SSL 证书"],
                &[
                    "代理连接",
                    "节点不稳定",
                    "网络连接问题",
                    "SSL 修复",
                    "连接超时",
                    "代理配置",
                ],
            ),
            topic(
                "ai-web-development",
                "ai-software",
                None,
                "网站与网页开发",
                "网站、网页、前端界面、托管与部署方案",
                &["网页开发", "网站开发", "网站部署"],
                &["GitHub Pages", "静态网站"],
                &[
                    "网页设计思路",
                    "个人网站方案",
                    "免费网站托管",
                    "网页前端",
                    "网站部署",
                    "网页交互",
                ],
            ),
            topic(
                "ai-mobile-development",
                "ai-software",
                None,
                "Android 与移动应用",
                "Android 应用、移动系统、ADB、兼容服务与手机端开发",
                &["Android 开发", "安卓应用开发", "移动应用开发"],
                &["Android 系统", "ADB 调试", "microG"],
                &[
                    "安卓开发",
                    "Android 应用",
                    "ADB 命令",
                    "移动端适配",
                    "安卓系统",
                    "手机端开发",
                ],
            ),
            topic(
                "ai-industry-business",
                "ai-software",
                None,
                "AI 产业与商业模式",
                "AI 行业竞争、市场格局、商业模式、风险与产业影响",
                &["AI 产业分析", "AI 商业模式", "AI 行业竞争"],
                &["AI 市场份额", "SaaS 行业"],
                &[
                    "AI 商业模式",
                    "AI 产业风险",
                    "AI 泡沫",
                    "AI 市场格局",
                    "AI 对 SaaS 的冲击",
                    "AI 经济影响",
                ],
            ),
            topic(
                "ai-knowledge-workflow",
                "ai-software",
                None,
                "知识库与检索",
                "本地优先知识库、搜索、证据和开放文件交换",
                &["个人知识库", "开放文件工作流"],
                &["SQLite 知识库", "Obsidian 知识库"],
                &["个人知识库", "全文检索", "知识证据链", "本地优先", "Markdown 交换"],
            ),
            topic(
                "vfx-compositing",
                "vfx",
                None,
                "合成工作流",
                "Fusion、颜色管理、镜头合成和复盘",
                &["Fusion 合成", "VFX 合成"],
                &["DaVinci Fusion", "Nuke 合成"],
                &["镜头合成", "预乘去边", "颜色空间管理", "ACES 色彩管理", "运动模糊合成"],
            ),
            topic(
                "vfx-animation",
                "vfx",
                None,
                "动画与动效",
                "动画设计、运动语言和界面动效",
                &["Motion Design", "动效设计"],
                &["After Effects 动效"],
                &["角色动画", "关键帧动画", "界面动效", "缓动曲线", "镜头转场"],
            ),
            topic(
                "vfx-transcription",
                "vfx",
                None,
                "音视频转写",
                "字幕、语音识别、时间码和内容整理",
                &["字幕整理", "视频转写"],
                &["Whisper 转写", "SRT 字幕", "VTT 字幕"],
                &["音频转写", "视频转写", "字幕时间码", "语音识别"],
            ),
            topic(
                "vfx-image-generation",
                "vfx",
                None,
                "AI 图像与视觉创作",
                "人物、场景、参考图和生成式视觉方案",
                &["AI 图像生成", "生成式视觉创作"],
                &["Midjourney", "Stable Diffusion"],
                &["生成画面", "参考图生成", "人物形象", "生成一张图片", "绘画提示词"],
            ),
            topic(
                "vfx-media-tools",
                "vfx",
                None,
                "音视频工具与下载",
                "视频下载、转码、播放、Cookies 与媒体处理工具",
                &["视频下载工具", "音视频处理工具", "媒体下载"],
                &["YouTube Cookies", "视频下载器"],
                &[
                    "视频下载功能",
                    "视频下载器",
                    "导出 Cookies",
                    "音视频转码",
                    "媒体处理",
                    "下载播放列表",
                ],
            ),
            topic(
                "design-brand-ui",
                "design",
                None,
                "品牌、图标与界面设计",
                "品牌识别、图标、Logo、界面、配色和视觉规范",
                &["品牌视觉设计", "图标设计", "界面视觉设计"],
                &["Logo 设计", "应用图标", "UI 设计"],
                &[
                    "批量改名设计",
                    "图标设计规范",
                    "软件配色方案",
                    "界面设计",
                    "品牌标识",
                    "扁平化图标",
                ],
            ),
            topic(
                "design-image-processing",
                "design",
                None,
                "图像处理与色彩",
                "图片扩展、修图、构图、色调、颜色和画面调整",
                &["图片处理", "画面调整", "色彩调整"],
                &["图像扩展", "色调调整"],
                &[
                    "图像扩展处理",
                    "画面色调调整",
                    "图片颜色调整",
                    "调整图片要求",
                    "构图调整",
                    "画面风格调整",
                ],
            ),
            topic(
                "design-creative-direction",
                "design",
                None,
                "创意方向与视觉方案",
                "参考风格、视觉方向、创意需求与方案评审",
                &["视觉创意方向", "风格设计", "创意方案"],
                &[],
                &[
                    "风格设计请求",
                    "视觉方案设计",
                    "设计方向",
                    "参考风格",
                    "视觉需求",
                    "创意评审",
                ],
            ),
            topic(
                "accounts-system",
                "accounts",
                None,
                "海外账号体系",
                "跨地区账号、身份区域、登录与服务可用性",
                &["跨区账号", "海外平台账号"],
                &["Apple ID 账号", "Google 账号"],
                &["美区 Apple ID", "港区 Apple ID", "账号地区", "跨区登录", "海外账号"],
            ),
            topic(
                "accounts-banking",
                "accounts",
                None,
                "海外银行与支付",
                "海外银行卡、银行账户、券商账户和跨境支付",
                &["海外银行卡", "美国银行卡", "香港银行卡"],
                &["HSBC HK", "Charles Schwab", "IBKR", "Wise", "PayPal"],
                &["海外银行", "银行卡申请", "借记卡方案", "信用卡方案", "跨境支付", "券商账户"],
            ),
            topic(
                "accounts-telecom",
                "accounts",
                None,
                "海外通信与号码",
                "境外手机卡、Wi-Fi Calling、漫游和号码保留",
                &["海外手机卡", "境外通信服务"],
                &["giffgaff", "Wi-Fi Calling", "VoLTE", "PayGo"],
                &["海外手机卡", "Wi-Fi Calling", "国际漫游", "手机号码保号", "eSIM 套餐"],
            ),
            topic(
                "accounts-risk",
                "accounts",
                None,
                "账号风控与封禁",
                "Google、Apple、支付和地区账号的登录与风控",
                &["海外账号风控", "账号被封"],
                &[],
                &["账号封禁", "登录验证失败", "风险控制", "账号申诉", "身份验证异常"],
            ),
            topic(
                "automotive-new-energy",
                "automotive",
                None,
                "新能源车与二手车",
                "新能源车型、购车选择、二手残值和长期用车",
                &["新能源车选购", "二手新能源车", "新能源车型比较"],
                &["理想 i8", "理想汽车", "极氪汽车", "特斯拉汽车"],
                &["新能源车", "二手车选择", "选车建议", "电池衰减", "车辆保值率", "用车成本"],
            ),
            topic(
                "automotive-selection",
                "automotive",
                None,
                "购车决策与车型比较",
                "车型、动力形式、空间、体验、价格与购车决策",
                &["车型比较", "购车选择", "选车分析"],
                &["MPV 与 SUV", "增程车"],
                &[
                    "车型对比",
                    "试驾对比",
                    "购车建议",
                    "汽车优缺点",
                    "车辆价格分析",
                    "动力形式选择",
                ],
            ),
            topic(
                "automotive-ownership",
                "automotive",
                None,
                "车辆功能与用车",
                "车辆功能、质保、售后、配件、养护与日常使用",
                &["车辆功能", "汽车售后", "日常用车"],
                &["车载记录仪", "车辆质保"],
                &[
                    "终身质保",
                    "车载功能",
                    "汽车配件",
                    "车辆售后",
                    "车载香薰",
                    "用车体验",
                ],
            ),
            topic(
                "automotive-driving-safety",
                "automotive",
                None,
                "驾驶安全与交通",
                "驾驶视野、车速、事故处理、证件与道路交通",
                &["驾驶安全", "道路交通", "事故处理"],
                &["电子驾驶证", "交通事故"],
                &[
                    "雨天驾驶",
                    "交通事故处理",
                    "表显车速",
                    "道路标志",
                    "驾驶证用途",
                    "行车安全",
                ],
            ),
            topic(
                "health-blood",
                "health",
                None,
                "血型与输血",
                "ABO/Rh 血型、红细胞和临床输血兼容",
                &["ABO 血型", "输血兼容"],
                &["A 型血", "B 型血", "O 型血", "AB 型血", "Rh 阴性"],
                &["血型输血", "红细胞输注", "输血反应", "ABO 血型", "交叉配血"],
            ),
            topic(
                "health-general",
                "health",
                None,
                "健康、疾病与就医",
                "症状、疾病、药物、检查、康复与就医建议",
                &["常见健康问题", "疾病与用药", "就医建议"],
                &["药物作用", "医学检查"],
                &[
                    "药物作用",
                    "疾病机制",
                    "检查结果",
                    "就医建议",
                    "症状缓解",
                    "康复建议",
                ],
            ),
            topic(
                "education-art",
                "education",
                None,
                "艺术与设计升学",
                "艺术、设计、数媒和动画专业的院校与志愿选择",
                &["艺术专业报考", "艺术设计升学", "美术专业报考"],
                &["视觉传达专业", "环境艺术设计", "数字媒体艺术"],
                &["艺术专业", "美术专业", "专科报考", "志愿填报", "录取分数", "艺术统考"],
            ),
            topic(
                "education-general",
                "education",
                None,
                "升学与专业选择",
                "高考、院校、分数线、专业方向与升学规划",
                &["高考升学", "专业选择", "院校报考"],
                &["高考分数线", "本科专业"],
                &[
                    "高考分数线",
                    "专业选择建议",
                    "院校选择",
                    "升学规划",
                    "录取统计",
                    "志愿方案",
                ],
            ),
            topic(
                "education-career",
                "education",
                None,
                "职业发展与岗位选择",
                "岗位、职业方向、工作机会、能力要求与发展决策",
                &["职业发展", "岗位选择", "求职决策"],
                &["岗位评估", "职业规划"],
                &[
                    "岗位评估",
                    "职业方向",
                    "工作选择",
                    "就业建议",
                    "职业规划",
                    "能力要求",
                ],
            ),
            topic(
                "life-nanjing-rent",
                "life",
                None,
                "南京租房",
                "区域、租金、通勤和居住环境比较",
                &["南京租房决策", "租房候选"],
                &["南京河西", "南京江宁"],
                &["南京租房", "租金预算", "通勤距离", "居住噪音", "小区停车"],
            ),
            topic(
                "life-equipment",
                "life",
                None,
                "设备与工作环境",
                "电脑、显示器、音频设备与工作空间",
                &["工作环境", "硬件设备"],
                &["Windows 工作站", "Mac 工作站"],
                &["电脑硬件", "显示器选择", "音频设备", "工作室噪音", "设备温度"],
            ),
            topic(
                "life-travel-visa",
                "life",
                None,
                "旅行、签证与行程",
                "目的地准备、签证、交通、住宿与旅行规划",
                &["旅行规划", "签证准备", "旅游行程"],
                &["美国签证", "新加坡旅行"],
                &[
                    "旅游准备",
                    "签证规划",
                    "旅行行程",
                    "出行准备",
                    "住宿选择",
                    "旅游建议",
                ],
            ),
            topic(
                "life-digital-services",
                "life",
                None,
                "数字服务与订阅",
                "会员、套餐、额度、订阅费用与数字服务选择",
                &["数字订阅服务", "会员与套餐", "订阅费用"],
                &["音乐会员", "AI 会员"],
                &[
                    "会员价格",
                    "订阅费用",
                    "会员升级",
                    "套餐区别",
                    "额度重置",
                    "数字服务",
                ],
            ),
            topic(
                "culture-law-family",
                "culture",
                None,
                "法律、家庭与社会关系",
                "法律责任、婚姻家庭、人际关系与社会规则",
                &["法律与家庭", "婚姻与风险", "社会关系"],
                &["举证责任", "婚姻关系"],
                &[
                    "法律责任",
                    "婚姻风险",
                    "家庭关系",
                    "育儿观念",
                    "陌生人私信",
                    "人际关系",
                ],
            ),
            topic(
                "culture-history-system",
                "culture",
                None,
                "历史、制度与社会观察",
                "历史人物、制度沿革、政策解释与社会现象",
                &["历史与制度", "社会观察", "政策解读"],
                &["历史官制", "政策时间表"],
                &[
                    "历史人物",
                    "古代官职",
                    "制度解释",
                    "政策方向",
                    "社会现象",
                    "历史背景",
                ],
            ),
            topic(
                "culture-entertainment",
                "culture",
                None,
                "影视、动漫与文化作品",
                "影视剧、动漫、人物、剧情、台词与文化内容",
                &["影视动漫", "文化作品", "剧情与人物"],
                &["影视角色", "动漫角色"],
                &[
                    "剧情解析",
                    "人物分析",
                    "动漫设定",
                    "影视作品",
                    "歌词内容",
                    "文化解读",
                ],
            ),
            topic(
                "culture-language",
                "culture",
                None,
                "语言、翻译与内容整理",
                "中外文翻译、文字转换、内容整理与表达优化",
                &["翻译与语言处理", "内容整理", "文字转换"],
                &["中文翻译", "英文翻译"],
                &[
                    "翻译成中文",
                    "页面翻译",
                    "截图翻译",
                    "整理文章内容",
                    "转成中文版本",
                    "表达优化",
                ],
            ),
        ],
    }
}

fn domain(key: &str, name: &str, description: &str) -> PersonalCatalogDomain {
    PersonalCatalogDomain {
        key: key.to_string(),
        name: name.to_string(),
        description: description.to_string(),
    }
}

fn topic(
    key: &str,
    domain_key: &str,
    parent_key: Option<&str>,
    name: &str,
    description: &str,
    aliases: &[&str],
    entities: &[&str],
    keywords: &[&str],
) -> PersonalCatalogTopic {
    PersonalCatalogTopic {
        key: key.to_string(),
        domain_key: domain_key.to_string(),
        parent_key: parent_key.map(str::to_string),
        name: name.to_string(),
        description: description.to_string(),
        topic_kind: "subject".to_string(),
        aliases: aliases.iter().map(|value| (*value).to_string()).collect(),
        entities: entities.iter().map(|value| (*value).to_string()).collect(),
        keywords: keywords.iter().map(|value| (*value).to_string()).collect(),
    }
}
